// <auto-generated />
using System;
using GofishApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GofishApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309025826_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GofishApi.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("TwoFactorMethod")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "seed-player-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-cstamp-1",
                            Email = "player1@gofish.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PLAYER1@GOFISH.COM",
                            NormalizedUserName = "PLAYER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEPRuzpiEVV+y1/C9a5xAPhLKQY+8j0xXXZSBKwLybnFVMZTL/46vRqgPu+M2vLNK0w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "seed-stamp-1",
                            TwoFactorEnabled = false,
                            TwoFactorMethod = 0,
                            UserName = "player1"
                        },
                        new
                        {
                            Id = "seed-player-2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-cstamp-2",
                            Email = "player2@gofish.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PLAYER2@GOFISH.COM",
                            NormalizedUserName = "PLAYER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEJatromC3gfgOMsbhaDqGqDpzaugG/Xq2SnUFU8TGKzBLeWk5l1TwhmkXC825DmIrg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "seed-stamp-2",
                            TwoFactorEnabled = false,
                            TwoFactorMethod = 0,
                            UserName = "player2"
                        },
                        new
                        {
                            Id = "seed-player-3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-cstamp-3",
                            Email = "player3@gofish.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PLAYER3@GOFISH.COM",
                            NormalizedUserName = "PLAYER3",
                            PasswordHash = "AQAAAAIAAYagAAAAEKgL7C5AzOAfa5vp0cKRncynUUGJjzu3R3+C0ejmq3ZqzAwb4QW0Svws9q2VGCtEOg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "seed-stamp-3",
                            TwoFactorEnabled = false,
                            TwoFactorMethod = 0,
                            UserName = "player3"
                        },
                        new
                        {
                            Id = "seed-player-4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-cstamp-4",
                            Email = "player4@gofish.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PLAYER4@GOFISH.COM",
                            NormalizedUserName = "PLAYER4",
                            PasswordHash = "AQAAAAIAAYagAAAAEOZY/m0PVegklAmoMsvIxwoWg6xAAsDl7VOY2CoHz5zeuUueQcxleuhlKkecj4hqIA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "seed-stamp-4",
                            TwoFactorEnabled = false,
                            TwoFactorMethod = 0,
                            UserName = "player4"
                        },
                        new
                        {
                            Id = "seed-player-5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-cstamp-5",
                            Email = "player5@gofish.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PLAYER5@GOFISH.COM",
                            NormalizedUserName = "PLAYER5",
                            PasswordHash = "AQAAAAIAAYagAAAAEC4ow372sQQSRDmaYoQpjLwS2TwK17WcaXrHFv2gO1E3etv7LBdWbpDdm6SDDC61rQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "seed-stamp-5",
                            TwoFactorEnabled = false,
                            TwoFactorMethod = 0,
                            UserName = "player5"
                        });
                });

            modelBuilder.Entity("GofishApi.Models.Friendship", b =>
                {
                    b.Property<string>("RequesterUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReceiverUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RepliedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("RequesterUserId", "ReceiverUserId");

                    b.HasIndex("ReceiverUserId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("GofishApi.Models.Pin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ExpiresAt", "CreatedAt");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("Pins", (string)null);

                    b.HasDiscriminator<int>("Kind");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GofishApi.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DownVotes")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("UpVotes")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            ImageUrl = "https://gofishstorage.blob.core.windows.net/post-images/0091b5cc-a77a-4b77-bb6d-c01d23b23ab5.png",
                            UpVotes = 0,
                            UserId = "seed-player-1"
                        },
                        new
                        {
                            Id = 2,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            ImageUrl = "https://gofishstorage.blob.core.windows.net/post-images/0091b5cc-a77a-4b77-bb6d-c01d23b23ab5.png",
                            UpVotes = 0,
                            UserId = "seed-player-2"
                        },
                        new
                        {
                            Id = 3,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            ImageUrl = "https://gofishstorage.blob.core.windows.net/post-images/0091b5cc-a77a-4b77-bb6d-c01d23b23ab5.png",
                            UpVotes = 0,
                            UserId = "seed-player-3"
                        },
                        new
                        {
                            Id = 4,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            ImageUrl = "https://gofishstorage.blob.core.windows.net/post-images/0091b5cc-a77a-4b77-bb6d-c01d23b23ab5.png",
                            UpVotes = 0,
                            UserId = "seed-player-4"
                        },
                        new
                        {
                            Id = 5,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            ImageUrl = "https://gofishstorage.blob.core.windows.net/post-images/0091b5cc-a77a-4b77-bb6d-c01d23b23ab5.png",
                            UpVotes = 0,
                            UserId = "seed-player-5"
                        },
                        new
                        {
                            Id = 6,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            ImageUrl = "https://gofishstorage.blob.core.windows.net/post-images/0091b5cc-a77a-4b77-bb6d-c01d23b23ab5.png",
                            UpVotes = 0,
                            UserId = "seed-player-1"
                        },
                        new
                        {
                            Id = 7,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            ImageUrl = "https://gofishstorage.blob.core.windows.net/post-images/0091b5cc-a77a-4b77-bb6d-c01d23b23ab5.png",
                            UpVotes = 0,
                            UserId = "seed-player-2"
                        },
                        new
                        {
                            Id = 8,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            ImageUrl = "https://gofishstorage.blob.core.windows.net/post-images/0091b5cc-a77a-4b77-bb6d-c01d23b23ab5.png",
                            UpVotes = 0,
                            UserId = "seed-player-3"
                        },
                        new
                        {
                            Id = 9,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            ImageUrl = "https://gofishstorage.blob.core.windows.net/post-images/0091b5cc-a77a-4b77-bb6d-c01d23b23ab5.png",
                            UpVotes = 0,
                            UserId = "seed-player-4"
                        },
                        new
                        {
                            Id = 10,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            ImageUrl = "https://gofishstorage.blob.core.windows.net/post-images/0091b5cc-a77a-4b77-bb6d-c01d23b23ab5.png",
                            UpVotes = 0,
                            UserId = "seed-player-5"
                        },
                        new
                        {
                            Id = 11,
                            Body = "Body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-1"
                        },
                        new
                        {
                            Id = 12,
                            Body = "Body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-2"
                        },
                        new
                        {
                            Id = 13,
                            Body = "Body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-3"
                        },
                        new
                        {
                            Id = 14,
                            Body = "Body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-4"
                        },
                        new
                        {
                            Id = 15,
                            Body = "Body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-5"
                        },
                        new
                        {
                            Id = 16,
                            Body = "Body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-1"
                        },
                        new
                        {
                            Id = 17,
                            Body = "Body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-2"
                        },
                        new
                        {
                            Id = 18,
                            Body = "Body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-3"
                        },
                        new
                        {
                            Id = 19,
                            Body = "Body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-4"
                        },
                        new
                        {
                            Id = 20,
                            Body = "Body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-5"
                        },
                        new
                        {
                            Id = 21,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-1"
                        },
                        new
                        {
                            Id = 22,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-2"
                        },
                        new
                        {
                            Id = 23,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-3"
                        },
                        new
                        {
                            Id = 24,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-4"
                        },
                        new
                        {
                            Id = 25,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-5"
                        },
                        new
                        {
                            Id = 26,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-1"
                        },
                        new
                        {
                            Id = 27,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-2"
                        },
                        new
                        {
                            Id = 28,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-3"
                        },
                        new
                        {
                            Id = 29,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-4"
                        },
                        new
                        {
                            Id = 30,
                            Body = "body",
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DownVotes = 0,
                            UpVotes = 0,
                            UserId = "seed-player-5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GofishApi.Models.CatchPin", b =>
                {
                    b.HasBaseType("GofishApi.Models.Pin");

                    b.Property<int?>("Bait")
                        .HasColumnType("int");

                    b.Property<string>("HookSize")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("Species")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(0);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 0,
                            Latitude = 38.512999999999998,
                            Longitude = -8.8729999999999993,
                            UserId = "seed-player-1",
                            Visibility = 0,
                            Bait = 1,
                            Species = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 0,
                            Latitude = 38.515000000000001,
                            Longitude = -8.8699999999999992,
                            UserId = "seed-player-2",
                            Visibility = 0,
                            Bait = 1,
                            Species = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 0,
                            Latitude = 38.518999999999998,
                            Longitude = -8.8629999999999995,
                            UserId = "seed-player-3",
                            Visibility = 0,
                            Bait = 1,
                            Species = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 0,
                            Latitude = 38.521999999999998,
                            Longitude = -8.8579999999999988,
                            UserId = "seed-player-4",
                            Visibility = 0,
                            Bait = 1,
                            Species = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 0,
                            Latitude = 38.533000000000001,
                            Longitude = -8.8529999999999998,
                            UserId = "seed-player-5",
                            Visibility = 0,
                            Bait = 1,
                            Species = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 0,
                            Latitude = 38.527999999999999,
                            Longitude = -8.847999999999999,
                            UserId = "seed-player-1",
                            Visibility = 0,
                            Bait = 1,
                            Species = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 0,
                            Latitude = 38.530999999999999,
                            Longitude = -8.843,
                            UserId = "seed-player-2",
                            Visibility = 0,
                            Bait = 1,
                            Species = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 0,
                            Latitude = 38.527000000000001,
                            Longitude = -8.859,
                            UserId = "seed-player-3",
                            Visibility = 0,
                            Bait = 1,
                            Species = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 0,
                            Latitude = 38.528999999999996,
                            Longitude = -8.8330000000000002,
                            UserId = "seed-player-4",
                            Visibility = 0,
                            Bait = 1,
                            Species = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 0,
                            Latitude = 38.530999999999999,
                            Longitude = -8.8549999999999986,
                            UserId = "seed-player-5",
                            Visibility = 0,
                            Bait = 1,
                            Species = 1
                        });
                });

            modelBuilder.Entity("GofishApi.Models.InfoPin", b =>
                {
                    b.HasBaseType("GofishApi.Models.Pin");

                    b.Property<int>("AccessDifficulty")
                        .HasColumnType("int");

                    b.Property<int>("Seabed")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(1);

                    b.HasData(
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 1,
                            Latitude = 38.512999999999998,
                            Longitude = -8.8729999999999993,
                            UserId = "seed-player-1",
                            Visibility = 0,
                            AccessDifficulty = 0,
                            Seabed = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 1,
                            Latitude = 38.513999999999996,
                            Longitude = -8.8780000000000001,
                            UserId = "seed-player-2",
                            Visibility = 0,
                            AccessDifficulty = 0,
                            Seabed = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 1,
                            Latitude = 38.518999999999998,
                            Longitude = -8.8769999999999989,
                            UserId = "seed-player-3",
                            Visibility = 0,
                            AccessDifficulty = 0,
                            Seabed = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 1,
                            Latitude = 38.518999999999998,
                            Longitude = -8.8819999999999997,
                            UserId = "seed-player-4",
                            Visibility = 0,
                            AccessDifficulty = 0,
                            Seabed = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 1,
                            Latitude = 38.524999999999999,
                            Longitude = -8.8809999999999985,
                            UserId = "seed-player-5",
                            Visibility = 0,
                            AccessDifficulty = 0,
                            Seabed = 1
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 1,
                            Latitude = 38.533000000000001,
                            Longitude = -8.8979999999999997,
                            UserId = "seed-player-1",
                            Visibility = 0,
                            AccessDifficulty = 0,
                            Seabed = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 1,
                            Latitude = 38.518999999999998,
                            Longitude = -8.8789999999999996,
                            UserId = "seed-player-2",
                            Visibility = 0,
                            AccessDifficulty = 0,
                            Seabed = 1
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 1,
                            Latitude = 38.527000000000001,
                            Longitude = -8.879999999999999,
                            UserId = "seed-player-3",
                            Visibility = 0,
                            AccessDifficulty = 0,
                            Seabed = 1
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 1,
                            Latitude = 38.521000000000001,
                            Longitude = -8.8809999999999985,
                            UserId = "seed-player-4",
                            Visibility = 0,
                            AccessDifficulty = 0,
                            Seabed = 1
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 1,
                            Latitude = 38.539999999999999,
                            Longitude = -8.891,
                            UserId = "seed-player-5",
                            Visibility = 0,
                            AccessDifficulty = 0,
                            Seabed = 1
                        });
                });

            modelBuilder.Entity("GofishApi.Models.WarnPin", b =>
                {
                    b.HasBaseType("GofishApi.Models.Pin");

                    b.Property<int>("WarningKind")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(2);

                    b.HasData(
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 2,
                            Latitude = 38.512999999999998,
                            Longitude = -8.8729999999999993,
                            UserId = "seed-player-1",
                            Visibility = 0,
                            WarningKind = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 2,
                            Latitude = 38.510999999999996,
                            Longitude = -8.8719999999999999,
                            UserId = "seed-player-2",
                            Visibility = 0,
                            WarningKind = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 2,
                            Latitude = 38.509,
                            Longitude = -8.8669999999999991,
                            UserId = "seed-player-3",
                            Visibility = 0,
                            WarningKind = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 2,
                            Latitude = 38.509999999999998,
                            Longitude = -8.8579999999999988,
                            UserId = "seed-player-4",
                            Visibility = 0,
                            WarningKind = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 2,
                            Latitude = 38.492999999999995,
                            Longitude = -8.8650000000000002,
                            UserId = "seed-player-5",
                            Visibility = 0,
                            WarningKind = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 2,
                            Latitude = 38.492999999999995,
                            Longitude = -8.8679999999999986,
                            UserId = "seed-player-1",
                            Visibility = 0,
                            WarningKind = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 2,
                            Latitude = 38.488999999999997,
                            Longitude = -8.8490000000000002,
                            UserId = "seed-player-2",
                            Visibility = 0,
                            WarningKind = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 2,
                            Latitude = 38.478000000000002,
                            Longitude = -8.8519999999999985,
                            UserId = "seed-player-3",
                            Visibility = 0,
                            WarningKind = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 2,
                            Latitude = 38.481000000000002,
                            Longitude = -8.8650000000000002,
                            UserId = "seed-player-4",
                            Visibility = 0,
                            WarningKind = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 3, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 2,
                            Latitude = 38.494999999999997,
                            Longitude = -8.863999999999999,
                            UserId = "seed-player-5",
                            Visibility = 0,
                            WarningKind = 1
                        });
                });

            modelBuilder.Entity("GofishApi.Models.Friendship", b =>
                {
                    b.HasOne("GofishApi.Models.AppUser", "Receiver")
                        .WithMany("ReceivedFriendships")
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GofishApi.Models.AppUser", "Requester")
                        .WithMany("RequestedFriendships")
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("GofishApi.Models.Pin", b =>
                {
                    b.HasOne("GofishApi.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("GofishApi.Models.Post", b =>
                {
                    b.HasOne("GofishApi.Models.Pin", "Pin")
                        .WithOne("Post")
                        .HasForeignKey("GofishApi.Models.Post", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GofishApi.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Pin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GofishApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GofishApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GofishApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GofishApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GofishApi.Models.AppUser", b =>
                {
                    b.Navigation("ReceivedFriendships");

                    b.Navigation("RequestedFriendships");
                });

            modelBuilder.Entity("GofishApi.Models.Pin", b =>
                {
                    b.Navigation("Post")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
