// species.enum.ts

export enum Species {
  Unknown = 0,
  Achiga = 1,
  Carp = 2,
  Catfish = 3,
  Pike = 4,
  Perch = 5,
  Trout = 6,
  Salmon = 7,
  Tilapia = 8,
  Tuna = 9,
  Cod = 10,
  Mackerel = 11,
  Sardine = 12,
  Anchovy = 13,
  Snook = 14,
  Grouper = 15,
  Swordfish = 16,
  Flounder = 17,
  Herring = 18,
  Shark = 19,
  Ray = 20,
  Eel = 21
}

export const SpeciesLabel: Record<Species, string> = {
  [Species.Unknown]: 'Unknown',
  [Species.Achiga]: 'Achiga',
  [Species.Carp]: 'Carp',
  [Species.Catfish]: 'Catfish',
  [Species.Pike]: 'Pike',
  [Species.Perch]: 'Perch',
  [Species.Trout]: 'Trout',
  [Species.Salmon]: 'Salmon',
  [Species.Tilapia]: 'Tilapia',
  [Species.Tuna]: 'Tuna',
  [Species.Cod]: 'Cod',
  [Species.Mackerel]: 'Mackerel',
  [Species.Sardine]: 'Sardine',
  [Species.Anchovy]: 'Anchovy',
  [Species.Snook]: 'Snook',
  [Species.Grouper]: 'Grouper',
  [Species.Swordfish]: 'Swordfish',
  [Species.Flounder]: 'Flounder',
  [Species.Herring]: 'Herring',
  [Species.Shark]: 'Shark',
  [Species.Ray]: 'Ray',
  [Species.Eel]: 'Eel',
};
